language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn test
deploy:
  provider: heroku
  skip_cleanup: true
  keep_history: true
  api_key:
    secure: "POTpU90ds2q/YcoHIHa7NSZJP0zjTvG7HE43/D4SnWfOPV2o9Un9CXY8pAv9G8PFyNWDAPfwVes8UVH4PksiKSy1+dWCaISlwZs5WDhRAkcltjT2xmg+zhQ3LGUoYkm+ZkRUSemxYUbM9OYprSdRGyMDJ8zeXtFgY9oU4vZVjC7FgxzuabwkaYY4uw2Ecf/goLx7sli7rjrEYdcLMa8PjG8OhO9qNVXHLEBZnZfdrIpwK9D5/ulvo0OZGmKw2sQZCg5Z4kIFhNe0bgTg0Sm4FdTYlVxZLfkzQUijYibUszRKe07JGH/nngAdIy3D6k/HIojplQ+WWJb79dyFqOt8uMIqg3R7iYzhSvqHnxa6ewD/d3yuhyrRXoS31j/9Nx3MHI65QGtwBhUhocBt0KspZi+uIJ1aeZZbjSkjxadiTmOZIY23sZ+cXYhsWrp4nmuN4k63Hs6khd8w2QkMSgYmYG/uLCIl+M6+tMEk8PubR1Iw5JXJ692joBaVLWGgXwQN3VUTXqz6ccinFVxvJIpspiNDDX/nBlgO/cTOHZur7jcWeZDi9H44RWvACY27kaY+Byv3Ikrj5BcXCkZk1ISkl3nghn23zR8lOedE0uN4JuTEHoPdc0ZSSmoU+2BNmvylhKstFYM2driJxHVFILVERp21HwqkNk8BMPrzQxIZJd4="
  app: peaceful-bastion-02967
  on:
    repo: DJ3-PM/roomie-backend