language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn test
deploy:
  provider: heroku
  skip_cleanup: true
  keep_history: true
  api_key:
    secure: UfJVQUQkyAuynHu1iIDk82y9lt2tQBogXHwLYBmTRe8L95QqyS1FVClOA9f0ZJ/wNcAyH+ZjxqlKVCtUUbWQvdKwm+2u+virL8dyomLd9qzO0Ptskdxgh1zh/I8OEfGT+uarQexIKlIiXe8yY5HEk5sofmv2Ap17sWYBMxZZUoNFNyj9/lgOJtrKnvRXX0fV4lBFF2/rnEIFD3K+DDP6uicN5GOjdt5jlopIeC5BP8mY5ZdBBNQbgg43gsGYQPV5/MRawzTle+XiRxmf8HiybD5R2AYJEcEmKlvIdS+HosYqTJ8L0Hb+BDbAewW2sSA1cD3xH8vjYX7yQ4bKV7AWnnjAELn7Npsb5El9VPAdkL7QG6RUbDomjxjnkKZyar1xO3rEJa7lUwrFiiGpG53Yo+lBjATo1VxqLePs/yaJVTDrNDEuLkS5Cy4orWHrWd5boAm8yzju6HQjB3EyMGbHsXD5HDOtAf142dQgrxLTqrGf7Gs0GGYhBkmhJlWO2B/lDx6Nx7JkQg38gqa53zZHKvleWF/TuV/Mdhr/03fts5xzQYWqxvobS5Zgk0TNGbcmSupaYeOAU8g+KJr5vjbu7ymYyGJqEXu/8EWzkkLySl8Gz0X1E7etQPjKzASBvC1gbtCDVGv2RQV9b2dEiuxwq+EKGfnSGlZIQybAeIy5Bzg=
  app: buscando-roomie 
  on:
    repo: DJ3-PM/roomie-backend